/** Common country names for the admin vendor form's HQ / supply-country selects. */
export const COUNTRIES: readonly string[] = [
  'United States',
  'Canada',
  'United Kingdom',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
  'Switzerland',
  'Poland',
  'Spain',
  'Italy',
  'Sweden',
  'Australia',
  'New Zealand',
  'Singapore',
  'Hong Kong',
  'Japan',
  'South Korea',
  'India',
  'China',
  'United Arab Emirates',
  'Israel',
  'South Africa',
  'Brazil',
  'Mexico',
];
